name: Android CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit testing
        run: |
          ./gradlew testDebugUnitTest

      - name: Build debug .apk
        run: |
          ./gradlew :sample-ci-libttt:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: sample-ci-libttt.aar
          path: sample-ci-libttt/build/outputs/aar/sample-ci-libttt-release.aar